### ISSUE TITLE
grab_contours possibly broken

### ISSUE THREAD

**Issue by leoll2** [jrosebr1/imutils#112] opened 2019-01-09 17:11 UTC
The function `grab_contours` in `imutils/convenience.py` was added in commit 5aae9887df3dcada5f8d8fa6af0df2122ad7aaca
The code contains a check on the length of `cnts`, and fails when it isn't 2 or 3. I guess the purpose is to discriminate between different OpenCV versions.
However, `cnts` is just a list containing all the contours, so its length is variable. Each element of `cnts` is a contour, and its length is variable as well (it is the number of points in the contour). Each point is a tuple of 2 elements (at least in my version, 3.4.3).
I think the function is broken, because the check should be on the item dimensions and not on the contours list itself.

**Comment by jrosebr1** [comment] 2019-01-09 19:01
Your understanding of the `cv2.findContours` function is partially correct, @leoll2.

Yes, the reason the `imutils` function was added was to handle how the `cv2.findContours` _return signature_ has changed between OpenCV versions.

The function is used like this:

```
cnts = cv2.findContours(...)
cnts = imutils.grab_contours(cnts)
```

The function is _not_ broken and works 100% as intended as it assumes that `cnts` is the full 2-tuple, 3-tuple, etc. output of `cv2.findContours`.

I'm going to go ahead and close this now but let me know if that makes sense.

**Closed by jrosebr1** 2019-01-09 19:01 UTC
