### ISSUE TITLE
Blocking use of WebcamVideoStream.read()

### ISSUE THREAD

**Issue by leogout** [jrosebr1/imutils#63] opened 2018-05-11 19:38 UTC
Hi, first of all, thanks for this library. I'm having a lot of fun using it with opencv.

While using the WebcamVideoStream class, I came across something odd. After calculation, I found out that my video loop was displaying ~280 fps. Actually I was looping and making calculations on the same image over and over :/
![screenshot from 2018-05-11 21-35-33](https://user-images.githubusercontent.com/9843962/39943491-483d2c7e-5563-11e8-844e-a533f936cecb.png)

After some researches I found [an article](https://www.pyimagesearch.com/2015/12/21/increasing-webcam-fps-with-python-and-opencv/) from you and in the comment section, people were making the same observations.

Sorry if I am misinterpreting your implementation, but this seems more like a bug to me than a feature.
I would like to make a PR to fix this behavior or at least let people choose if they want to wait for the frame or if they prefer requesting the same image over and over (which is a bit odd to me).

Have a nice day, cheers !

**Comment by leogout** [comment] 2018-05-11 19:51
Thinking about it, using a separate thread may be a waste of resources. While using heavy computational resources to process images, say, 5 times per second, our cam thread is reading its images one after the other at 30 fps while no one is requesting for them. I think i'll just stick with the old way of reading images in the main loop :)
Thanks anyway, cheers !

**Comment by jrosebr1** [comment] 2018-05-11 20:50
> Sorry if I am misinterpreting your implementation, but this seems more like a bug to me than a feature.

Hey, thanks for taking the time to comment on the library, I appreciate it.

**However, this is a _feature_ not a _bug_.**

I've addressed this a few times in the comments section of a few blog posts so it's probably worth including a line about it in the source code but for the vast majority of implementations of real-world computer vision pipelines you will not be processing the same frame multiple times. For highly simplistic operations, yes, totally possible -- but that's an outlier situation. Adding additional code to check for a brand new frame each and every time would further slow down the more "real-world" implementations of problems.

Here I'm defining "real-world" as more computationally heavy, of course. Its totally possible that highly simplistic operations can solve real-world problems in some situations, but if your pipeline is running that fast you would be better off use a blocking `cv2.VideoCapture` to ensure you grab a brand new frame, but again, that's an outlier situation and not why this class was designed.

I hope that makes sense. I'm going to close this issue per the reasons above but I'll keep monitoring if you have any questions 😄

**Closed by jrosebr1** 2018-05-11 20:50 UTC
